# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('psc', ['energy', 'mobility', 'network', 'antenna', 'buildings', 'lte'])
    module.source = [
        'model/uav-mobility-energy-model.cc',
        'model/udp-group-echo-server.cc',
        'helper/uav-mobility-energy-model-helper.cc',
        'helper/udp-group-echo-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('psc')
    module_test.source = [
        'test/uav-mobility-energy-model-test.cc',
        'test/uav-mobility-energy-model-helper-test.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'psc'
    headers.source = [
        'model/uav-mobility-energy-model.h',
        'model/udp-group-echo-server.h',
        'helper/uav-mobility-energy-model-helper.h',
        'helper/udp-group-echo-helper.h',
        ]

    if (bld.env['ENABLE_EXAMPLES']):
        bld.recurse('examples')

    # bld.ns3_python_bindings()

