# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('psc', ['energy', 'mobility', 'network', 'antenna', 'buildings', 'lte'])
    module.source = [
        'model/intel-http-client.cc',
        'model/intel-http-header.cc',
        'model/intel-http-server.cc',
        'model/mcptt-msg.cc',
        'model/mcptt-floor-msg.cc',
        'model/mcptt-media-msg.cc',
        'model/mcptt-media-src.cc',
        'model/mcptt-pusher.cc',
        'model/mcptt-floor-machine.cc',
        'model/mcptt-floor-machine-basic.cc',
        'model/mcptt-ptt-app.cc',
        'model/mcptt-floor-msg-field.cc',
        'model/mcptt-queued-user-info.cc',
        'model/mcptt-timer.cc',
        'model/mcptt-counter.cc',
        'model/mcptt-floor-queue.cc',
        'model/mcptt-floor-machine-basic-state.cc',
        'model/mcptt-rtp-header.cc',
        'model/mcptt-entity-id.cc',
        'model/mcptt-call-msg-field.cc',
        'model/mcptt-call-msg.cc',
        'model/mcptt-call-machine.cc',
        'model/mcptt-call-machine-grp-basic.cc',
        'model/mcptt-call-machine-grp-basic-state.cc',
        'model/mcptt-call-machine-grp-broadcast.cc',
        'model/mcptt-call-machine-grp-broadcast-state.cc',
        'model/mcptt-call-machine-private.cc',
        'model/mcptt-call-machine-private-state.cc',
        'model/mcptt-call-type-machine.cc',
        'model/mcptt-call-type-machine-grp-basic.cc',
        'model/mcptt-call-type-machine-private.cc',
        'model/mcptt-call-type-machine-private-state.cc',
        'model/mcptt-emerg-alert-machine.cc',
        'model/mcptt-emerg-alert-machine-basic.cc',
        'model/mcptt-chan.cc',
        'model/mcptt-call.cc',
        'helper/intel-http-helper.cc',
        'helper/mcptt-helper.cc',
        'helper/mcptt-msg-stats.cc',
        'helper/mcptt-state-machine-stats.cc',
        'model/uav-mobility-energy-model.cc',
        'model/udp-group-echo-server.cc',
        'helper/uav-mobility-energy-model-helper.cc',
        'helper/udp-group-echo-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('psc')
    module_test.source = [
        'test/intel-http-model-test.cc',
        'test/mcptt-call-control-broadcast.cc',
        'test/mcptt-call-control-private.cc',
        'test/mcptt-call-control.cc',
        'test/mcptt-call-control-msg.cc',
        'test/mcptt-call-type-control-private.cc',
        'test/mcptt-call-type-control.cc',
        'test/mcptt-floor-control.cc',
        'test/mcptt-floor-control-msg.cc',
        'test/mcptt-msg-dropper.cc',
        'test/mcptt-test-app.cc',
        'test/mcptt-test-case-config.cc',
        'test/mcptt-test-case.cc',
        'test/uav-mobility-energy-model-test.cc',
        'test/uav-mobility-energy-model-helper-test.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'psc'
    headers.source = [
        'model/intel-http-client.h',
        'model/intel-http-header.h',
        'model/intel-http-server.h',
        'model/mcptt-media-sink.h',
        'model/mcptt-pushable.h',
        'model/mcptt-floor-msg.h',
        'model/mcptt-media-src.h',
        'model/mcptt-pusher.h',
        'model/mcptt-floor-machine.h',
        'model/mcptt-floor-machine-basic.h',
        'model/mcptt-ptt-app.h',
        'model/mcptt-msg.h',
        'model/mcptt-media-msg.h',
        'model/mcptt-floor-msg-field.h',
        'model/mcptt-queued-user-info.h',
        'model/mcptt-timer.h',
        'model/mcptt-counter.h',
        'model/mcptt-floor-queue.h',
        'model/mcptt-floor-machine-basic-state.h',
        'model/mcptt-rtp-header.h',
        'model/mcptt-entity-id.h',
        'model/mcptt-call-msg-field.h',
        'model/mcptt-call-msg.h',
        'model/mcptt-call-machine.h',
        'model/mcptt-call-machine-grp-basic.h',
        'model/mcptt-call-machine-grp-basic-state.h',
        'model/mcptt-call-machine-grp-broadcast.h',
        'model/mcptt-call-machine-grp-broadcast-state.h',
        'model/mcptt-call-machine-private.h',
        'model/mcptt-call-machine-private-state.h',
        'model/mcptt-call-type-machine.h',
        'model/mcptt-call-type-machine-grp-basic.h',
        'model/mcptt-call-type-machine-private.h',
        'model/mcptt-call-type-machine-private-state.h',
        'model/mcptt-emerg-alert-machine.h',
        'model/mcptt-emerg-alert-machine.h',
        'model/mcptt-emerg-alert-machine-basic.h',
        'model/mcptt-chan.h',
        'model/mcptt-call.h',
        'helper/intel-http-helper.h',
        'helper/mcptt-helper.h',
        'helper/mcptt-msg-stats.h',
        'helper/mcptt-state-machine-stats.h',
        'model/uav-mobility-energy-model.h',
        'model/udp-group-echo-server.h',
        'helper/uav-mobility-energy-model-helper.h',
        'helper/udp-group-echo-helper.h',
        ]

    if (bld.env['ENABLE_EXAMPLES']):
        bld.recurse('examples')

    # bld.ns3_python_bindings()

