#!/bin/bash
#
# SPDX-License-Identifier: NIST-Software
#
# Author:  Aziza Ben Mosbah (aziza.benmosbah@nist.gov)

# This file is used to plot UE positions as traced in the NrSlUePositionTrace.txt file
# This trace can be generated by NrSlTraceHelper::TraceUePositions()
# The script is invoked with a single argument: the trace file (usually NrSlUePositionTrace.txt)
# The output file is named 'ue-positions.pdf'.  The script requires gnuplot to be installed.

if ! command -v gnuplot &> /dev/null
then
    echo "Error: gnuplot not found"
    exit 1
fi

uePositionsFile=$1

if [ "$#" -ne 1 ]; then
    echo "Error: You must provide the node positions file as the only argument"
    exit 1
fi

if ! [ -f ${uePositionsFile} ]; then
  echo "Error: Trace file does not exist"
  exit 1
fi

ueNum=`cat ${uePositionsFile} | awk 'BEGIN{n=0} {if ($1==0) {n+=1}} END{print n}'`
for i in $(seq 1 ${ueNum}); do rm -f position${i}.txt; cat ${uePositionsFile} | awk -v ue=${i} '{if ($2==ue) {print $0}}' >> position${i}.txt; done

echo "Plotting node positions ... "
ext="pdf"
figure="ue-positions.${ext}"
rm -f ${figure}
gnuplot -persist << EOF
set terminal ${ext}
set out "${figure}"
set style line 81 lt 0
set grid back linestyle 81
set border 3
set xtics nomirror
set ytics nomirror
unset surface
set autoscale
unset log
unset label
set xtic auto
set ytic auto
set key off
set xlabel "X (m)"
set ylabel "Y (m)"
set key outside font "Verdana, 9"
plot for [i=1:${ueNum}] 'position'.i.'.txt' using 3:4 title 'UE '.i
EOF

for i in $(seq 1 ${ueNum}); do rm -f position${i}.txt; done
