.. [TS24334] 3GPP TS 24.334 "Proximity-services (ProSe) User Equipment (UE) to ProSe function protocol aspects; Stage 3"

.. [TS23303] 3GPP TS 23.303 "Technical Specification Group Services and System Aspects; Proximity-based services (ProSe); Stage 2"

.. [TS23003] 3GPP TS 23.003 "Technical Specification Group Core Network and Terminals; Numbering, addressing and identification; V15"

.. [TR36814] 3GPP TR 36.814 "E-UTRA Further advancements for E-UTRA physical layer aspects"

.. [TR36843] 3GPP TR 36.843 "Study on LTE Device to Device Proximity Services; Radio Aspects"

.. [TS36331] 3GPP TS 36.331 "Evolved Universal Terrestrial Radio Access (E-UTRA); Radio Resource Control (RRC); Protocol specification"

.. [TS36300] 3GPP TS 36.300 "Evolved Universal Terrestrial Radio Access (E-UTRA) and Evolved Universal Terrestrial Radio Access Network (E-UTRAN); Overall description; Stage 2"

.. [TS36323] 3GPP TS 36.323 "Evolved Universal Terrestrial Radio Access (E-UTRA); Packet Data Convergence Protocol (PDCP) specification"

.. [TS36212] 3GPP TS 36.212 "Evolved Universal Terrestrial Radio Access (E-UTRA); Multiplexing and channel coding"

.. [TS36213] 3GPP TS 36.213 "Evolved Universal Terrestrial Radio Access (E-UTRA); Physical layer procedures"

.. [TS36322] 3GPP TS 36.322 "Evolved Universal Terrestrial Radio Access (E-UTRA); Radio Link Control (RLC) protocol specification"

.. [TS36214] 3GPP TS 36.214 "Evolved Universal Terrestrial Radio Access (E-UTRA); Physical layer; Measurements" 

.. [TS25814] 3GPP TS 25.814 "Physical layer aspect for evolved Universal Terrestrial Radio Access (UTRA)"

 
.. [NIST2016] Rouil, R., Cintrón, F.J., Ben Mosbah, A. and Gamboa, S., 
   `"An LTE Device-to-Device module for ns-3"
   <https://www.nist.gov/publications/lte-device-device-module-ns-3/>`_, 
   in Proceedings of the Workshop on ns-3, 15-16 June 2016, Seattle
   (Washington).

.. [NIST2017] Rouil, R., Cintrón, F.J., Ben Mosbah, A. and Gamboa, S., 
   `"Implementation and Validation of an LTE D2D Model for ns-3"
   <https://www.nist.gov/publications/implementation-and-validation-lte-d2d-model-ns-3/>`_, 
   in Proceedings of the Workshop on ns-3, 13-14 June 2017, Porto
   (Portugal).

.. [NISTBLERD2D] J. Wang, R. Rouil `"BLER Performance Evaluation of LTE Device-to-Device Communications.
   Technical Report. National Institute of Standards and Technology, Gaithersburg, MD."
   <https://www.nist.gov/publications/bler-performance-evaluation-lte-device-device-communications>`_,.

.. [NISTFREQHOPP] Cintrón, F.J., `"Performance Evaluation of LTE Device-to-Device Out-of-Coverage Communication
   with Frequency Hopping Resource Scheduling"
   <https://nvlpubs.nist.gov/nistpubs/ir/2018/NIST.IR.8220.pdf>`_,.

.. [NIST2019] Gamboa, S., Thanigaivel, R. and Rouil, R.,
   `"System Level Evaluation of UE-to-Network Relays in D2D-enabled LTE Networks"
   <https://www.nist.gov/publications/system-level-evaluation-ue-network-relays-d2d-enabled-lte-networks/>`_,
   in Proceedings of the 2019 IEEE 24th International Workshop on Computer 
   Aided Modeling and Design of Communication Links and Networks,
   11-13 September 2019, Limassol (Cyprus).
